# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d0e74673c51dc242ff7006a100de6a8"
name = "shakingcat-test"
application_url = "https://qualifying-himself-late-var.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shakingcat-test.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://qualifying-himself-late-var.trycloudflare.com/auth/callback",
  "https://qualifying-himself-late-var.trycloudflare.com/auth/shopify/callback",
  "https://qualifying-himself-late-var.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
